# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: PiGames Blog
email: pigames.team@gmail.com
description: Learn about all the cool stuff that PiGames crew do! We love making HTML5 games, desktop games and robots. We write our code mainly in JavaScript, C++ and C#.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://pigames.github.io/blog" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: pigames
github_username:  pigames

date_format: "%d %B %Y"
date_format_datetime: "%Y-%m-%dT%T%z"
disqus:
  shortname: "blog-pigam-es"
google_analytics: "UA-100013183-1"

post_desc_p: 1

# Build settings
markdown: kramdown

paginate: 5

kramdown:
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    disable: true

gems:
  - jekyll-feed
  - jemoji
  - jekyll-paginate
exclude:
  - Gemfile
  - Gemfile.lock

defaults:
  -
    values:
      layout: "default"
